services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stack_base_frontend
    container_name: stack_base_frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env.local
